#!/bin/sh
#

if git ls-files -u | grep -q .; then
echo "⚠️  Merge in progress. Skipping Prettier to avoid issues."
  exit 0
fi

find src -name .DS_Store -exec rm {} \;

npx nx affected --target=lint,test,build  --base=origin/develop --head=HEAD

npm run prettier-staged

STAGED_FILES=$(git diff --name-only --cached --diff-filter=ACM | grep -E '\.(html|ts|scss|css|json)$')

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi

