#!/bin/sh
#

git stash -q --keep-index

find {apps,libs} -name .DS_Store -exec rm {} \; && nx format:write --all && git add . && npx nx affected --t lint test build --base=origin/develop --head=HEAD

status=$?

git stash pop -q

exit $status
